version: '3.8'

services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://judge0:YourPassword123@db:5432/judge0
      - REDIS_URL=redis://redis:6379

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://judge0:YourPassword123@db:5432/judge0
      - REDIS_URL=redis://redis:6379

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: YourPassword123
      POSTGRES_DB: judge0
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: